/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Set of artifact families to produce; each entry maps to one or more files. */
export type EmitTarget = 'models' | 'angular';
export declare const EmitTarget: {
  readonly Models: 'models';
  readonly Angular: 'angular';
};

/**
 * One generated artifact. `contents` carries the emitted source whether
 * or not the caller also asked for it on disk.
 */
export interface GeneratedArtifact {
  path: string
  contents: string
}

/**
 * Payload returned inside `GenerateOutcome.error`, which the JS wrapper
 * turns into a `GenerateError`. The fatal sits at the top level;
 * pre-fatal warnings ride in `warnings`.
 */
export interface GenerateErrorPayload {
  code: DiagnosticCode
  subcode: DiagnosticSubcode | null
  message: string
  path: string
  warnings: Array<GeneratorDiagnostic>
}

export interface GenerateOptions {
  /**
   * Path to the spec on disk. Mutually exclusive with `input_contents`;
   * the option validator rejects requests that set both or neither.
   */
  inputPath?: string
  /**
   * Raw spec source. When set, `display_path` is required and the
   * 16 MiB byte cap applies to `input_contents.as_bytes().len()`.
   */
  inputContents?: string
  /**
   * Banner and diagnostic display string. Required with
   * `input_contents`, ignored with `input_path`.
   */
  displayPath?: string
  /**
   * Decoder hint. Only honoured when `input_contents` is set; combining
   * it with `input_path` is a shape error.
   */
  inputFormat?: InputFormat
  /**
   * Optional. When undefined, generation runs in-memory (no files written).
   * Passing an empty string is rejected at option resolution.
   */
  outputPath?: string
  emit?: Array<EmitTarget>
  mappedTypes?: Array<MappedType>
  /**
   * Per-content-type override of the response-decoding kind
   * (`json | blob | text | arrayBuffer`).
   */
  responseTypeMapping?: Array<ResponseTypeMapping>
  naming?: NamingConfig
  /**
   * Angular output layouts. Defaults to `['services']`; only meaningful
   * with the `angular` emit target.
   */
  layout?: Array<Layout>
}

export interface GenerateResult {
  summary: GenerateSummary
  diagnostics: Array<GeneratorDiagnostic>
  artifacts: Array<GeneratedArtifact>
}

export interface GenerateSummary {
  /**
   * The source spec's path as supplied, with separators normalised and
   * nothing resolved. The same string appears in every diagnostic's
   * `path`.
   */
  normalizedSourcePath: string
  specVersion: string
  title: string
  pathCount: number
  operationCount: number
  schemaCount: number
}

/**
 * Boundary projection of [`Diagnostic`] for the NAPI surface, where
 * `code` and `severity` are strings a JS consumer compares against.
 *
 * `severity` is `"warning"` or `"error"`. `subcode` is set only for
 * `PolicyViolation`.
 */
export interface GeneratorDiagnostic {
  code: DiagnosticCode
  subcode: DiagnosticSubcode | null
  severity: 'warning' | 'error'
  message: string
  path: string
}

/**
 * Explicit decoder selection. Skips both extension-based detection and
 * the JSON-then-YAML sniff fallback. Honoured only with `input_contents`.
 */
export type InputFormat = 'json' | 'yaml';
export declare const InputFormat: {
  readonly Json: 'json';
  readonly Yaml: 'yaml';
};

/**
 * One Angular output layout: the per-tag class (`services`) or one file
 * per operation plus a barrel (`operations`). Listing both emits the
 * classes on top of the operation files.
 */
export type Layout = 'services' | 'operations';
export declare const Layout: {
  readonly Services: 'services';
  readonly Operations: 'operations';
};

/**
 * Replaces the generated declaration for `schema` with `type_name`,
 * imported from `import`. Crosses the NAPI boundary as `type`.
 */
export interface MappedType {
  schema: string
  import: string
  type: string
  alias?: string
}

export interface NamingChainItem {
  string?: string
  rule?: NamingRuleEntry
}

/**
 * The naming config as it crosses the NAPI boundary, where a JS `RegExp`
 * arrives already unpacked into `{ source, flags }`.
 */
export interface NamingOptions {
  methodName?: NamingValue
  group?: NamingValue
}

export interface NamingParseSpec {
  source: string
  flags: string
}

export interface NamingRuleEntry {
  from?: string
  parse?: NamingParseSpec
  format?: string
  /** Lowercase per spec: 'camel' | 'pascal' | 'snake' | 'kebab' | 'constant'. */
  case?: string
}

/**
 * A string shorthand, a single rule, or a chain of either. Exactly one
 * field must be set; `plan::naming::lower` enforces that.
 */
export interface NamingValue {
  /** `{ string: '...' }` — bare format-string shorthand. */
  string?: string
  /** `{ rule: { ... } }` — a single Rule. */
  rule?: NamingRuleEntry
  /** `{ chain: [...] }` — a sequence of `{ string }` or `{ rule }`. */
  chain?: Array<NamingChainItem>
}

/** How a response body is decoded, named as the JS runtime names it. */
export type ResponseType = 'json' | 'blob' | 'text' | 'arrayBuffer';
export declare const ResponseType: {
  readonly Json: 'json';
  readonly Blob: 'blob';
  readonly Text: 'text';
  readonly ArrayBuffer: 'arrayBuffer';
};

/**
 * Overrides the decoded response kind for one content type, matched
 * case-insensitively against the media type the spec declares.
 */
export interface ResponseTypeMapping {
  contentType: string
  responseType: ResponseType
}

// Hand-authored tail concatenated onto the napi-rs-generated index.d.ts
// by scripts/patch-types.mjs. Contains TS surface that napi-rs cannot
// emit on its own (named string-literal unions, the GenerateError class
// defined in lib/generate-error.js).

/**
 * Diagnostic code taxonomy. Each value maps 1:1 to a Rust DiagnosticCode,
 * except `E_UNEXPECTED` and `E_UNSUPPORTED_RUNTIME`, which are reserved
 * for the JS wrappers:
 *   - `E_UNEXPECTED` is a defensive fallback when a `GenerateError` is
 *     constructed without an explicit `code`.
 *   - `E_UNSUPPORTED_RUNTIME` is thrown by the browser entry when the
 *     WebAssembly binding cannot be loaded.
 *
 * `E_INVALID_OPTION` covers both wrapper-side shape rejections (a JS
 * caller passed an option whose type/shape is wrong — surfaced with
 * `subcode: 'shape'`) and Rust-side semantic rejections of option values
 * (surfaced with no subcode).
 */
export type DiagnosticCode =
  | 'E_INPUT_INVALID'
  | 'E_UNSUPPORTED_SEMANTIC'
  | 'E_UNSUPPORTED_RUNTIME'
  | 'E_INVALID_REFERENCE'
  | 'E_INVALID_OPTION'
  | 'E_POLICY_VIOLATION'
  | 'E_WRITE_FAILED'
  | 'E_UNEXPECTED';

/**
 * Finer-grained taxonomy projected from `Diagnostic.subcode`. Emitted for
 * `E_POLICY_VIOLATION` diagnostics, a subset of `E_UNSUPPORTED_SEMANTIC`
 * warnings, and wrapper-side `E_INVALID_OPTION` shape rejections
 * (`'shape'`) so consumers can route remediation without parsing the
 * message. Null for every diagnostic that does not carry a sub-class.
 */
export type DiagnosticSubcode =
  | 'shape'
  | 'missing-operation-id'
  | 'missing-tag'
  | 'field-collision'
  | 'missing-discriminator-property'
  | 'discriminator-property-must-be-string'
  | 'invalid-form-field-name'
  | 'invalid-path-parameter-name'
  | 'missing-body-schema'
  | 'unsupported-parameter-location'
  | 'duplicate-operation-id'
  | 'duplicate-schema-name'
  | 'format-dropped'
  | 'schema-cap-exceeded'
  | 'operation-cap-exceeded'
  | 'mapping-expansion-exceeded'
  | 'naming-resolution'
  | 'reserved-identifier'
  | 'multi-content-body'
  | 'unsupported-body-content-type'
  | 'multipart-nested-object'
  | 'multipart-composed-field'
  | 'multipart-non-object-body'
  | 'multipart-open-schema'
  | 'urlencoded-binary-field'
  | 'urlencoded-nested-object'
  | 'urlencoded-composed-field'
  | 'urlencoded-non-object-body'
  | 'urlencoded-open-schema';

/**
 * Thrown by `generate` on any fatal diagnostic. Real JS class
 * that extends `Error`, so consumers can write `err instanceof
 * GenerateError`.
 *
 * Defined in `lib/generate-error.js`. The native binding returns the
 * payload as data; the JS wrappers (`lib/index.js`, `lib/browser.js`)
 * construct and throw this class.
 */
export declare class GenerateError extends Error {
  constructor(payload: GenerateErrorPayload);
  readonly code: DiagnosticCode;
  readonly subcode: DiagnosticSubcode | null;
  readonly path: string;
  readonly warnings: Array<GeneratorDiagnostic>;

  /**
   * Cross-realm-safe predicate. `instanceof GenerateError` only matches
   * inside the realm where `openapi-ng` was loaded (a different vm
   * context / worker thread / iframe has a different class identity).
   * The internal sentinel survives the realm boundary, so consumers
   * who run across realms should prefer this check.
   */
  static isGenerateError(value: unknown): value is GenerateError;
}

/**
 * Case transformations supported by naming rules (see `docs/naming-spec.md`).
 */
export type Case = 'camel' | 'pascal' | 'snake' | 'kebab' | 'constant';

/**
 * One rule in a naming chain. All four fields are optional. The
 * evaluation order is: expand `from` → match `parse` → expand `format`
 * (defaults to expanded `from` when omitted; required when `parse` is
 * present) → apply `case`. A rule fails when any template reference is
 * unbound or `parse` does not match.
 */
export interface NamingRule {
  from?: string;
  parse?: RegExp;
  format?: string;
  case?: Case;
}

/**
 * A bare string is shorthand for `{ format: string }` with no case
 * transformation. An array is a fallback chain — the first rule that
 * does not fail wins; if every rule fails the generation errors with
 * `E_POLICY_VIOLATION` subcode `'naming-resolution'`.
 */
export type Naming = string | NamingRule | Array<NamingRule | string>;

export interface NamingConfig {
  methodName?: Naming;
  group?: Naming;
}

/**
 * File-config shape — accepted by `.openapi-ng.{yaml,json}`,
 * `openapi-ng.config.{ts,mts,cts,mjs,js,cjs}`, and the `defineConfig`
 * helper. Keys mirror the YAML/JSON surface (`input`/`output`), NOT
 * the programmatic `generate({ inputPath, outputPath, ... })` surface.
 */
export interface Config {
  input?: string;
  output?: string;
  emit?: Array<EmitTarget>;
  mappedTypes?: Array<MappedType>;
  responseTypeMapping?: Array<ResponseTypeMapping>;
  naming?: NamingConfig;
  layout?: Array<Layout>;
}

/**
 * Generate TypeScript artifacts from an OpenAPI 3.x document. Resolves
 * with the summary, warnings and artifacts; rejects with `GenerateError`
 * on any fatal diagnostic.
 */
export declare function generate(options: GenerateOptions): Promise<GenerateResult>;

/**
 * Identity helper that anchors TypeScript inference for JS/TS configs:
 *   import { defineConfig } from '@avsystem/openapi-ng/config';
 *   export default defineConfig({ input: 'spec.yaml', output: 'out' });
 *
 * Returns its argument unchanged. Has no runtime behaviour.
 *
 * Declared here so the `./config` subpath export resolves to the same
 * `.d.ts` file (one published types surface).
 */
export declare function defineConfig(config: Config): Config;
