import test, { type ExecutionContext } from 'ava';
import fs from 'node:fs';
import { createRequire } from 'node:module';
import os from 'node:os';
import path from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

// Import from the package root (resolves to lib/index.js via package.json
// `main`), not the native binding directly — the wrapper is what upgrades
// thrown plain errors into `GenerateError` class instances.
import { generate, GenerateError } from '../lib/index.js';
import { __setFetchImplForTest } from '../lib/fetch-input.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Pass fixtures as paths relative to CWD (project root) so display_path
// returns a short, machine-independent path in banners and diagnostics.
const fixture = (name: string) => path.join('test', 'fixtures', name);

// `angular-consumer/generated/` is shared by every test that emits and
// type-checks real output, so a test writing there must first call
// `resetAngularConsumerGeneratedDir()`, and a tree that must survive the
// wipe belongs in its own sibling directory with its own tsconfig.
const angularConsumerGeneratedDir = path.join(__dirname, 'angular-consumer', 'generated');

function resetAngularConsumerGeneratedDir() {
  fs.rmSync(angularConsumerGeneratedDir, { recursive: true, force: true });
  fs.mkdirSync(angularConsumerGeneratedDir, { recursive: true });
}

async function withTempDir(run: (dir: string) => void | Promise<void>) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'openapi-ng-generate-'));
  try {
    await run(dir);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function stripBanner(contents: string | undefined): string {
  return (contents ?? '').replace(
    /^\/\/ Generated by openapi-ng v[^\n]*\n\/\/ Source: [^\n]*\n\/\/ DO NOT EDIT[^\n]*\n\n/u,
    '',
  );
}

// Default emit selection.
const DEFAULT_EMIT = ['models', 'angular'] as const;
const FULL_EMIT = ['models', 'angular'] as const;

const expectedModelSource = [
  'export interface Pet {',
  '  id: PetId;',
  '  name: string;',
  '  status: PetStatus;',
  '  tags: Tag[];',
  '  nickname?: string | null;',
  '}',
  '',
  'export type PetId = string;',
  '',
  'export type PetList = Pet[];',
  '',
  "export type PetStatus = 'available' | 'pending' | 'sold';",
  '',
  'export interface Tag {',
  '  id: number;',
  '  label: string;',
  '}',
  '',
  'export interface UpdatePetRequest {',
  '  status: PetStatus;',
  '  tagIds: number[];',
  '  nickname?: string | null;',
  '}',
  '',
].join('\n');

// Paths echoed back by generate() are forward-slashed on every platform,
// which is why these assert against the normalized form and not
// `path.join`.
const unsupportedSemanticDiagnostic = {
  code: 'E_UNSUPPORTED_SEMANTIC',
  severity: 'error',
  message:
    'Unsupported OpenAPI semantic shape: property schema EventEnvelope composition member 2.data must define additionalProperties as a schema object.',
  path: 'test/fixtures/unsupported-semantic.openapi.yaml',
};

const unsupportedRootDiagnostic = {
  code: 'E_INPUT_INVALID',
  severity: 'error',
  message:
    'Failed to decode OpenAPI input as YAML: components.schemas: invalid type: sequence, expected a map at line 8 column 5',
  path: 'test/fixtures/unsupported-root.yaml',
};

function artifactPaths(result: { artifacts: Array<{ path: string }> }) {
  return result.artifacts.map(artifact => artifact.path);
}

interface Artifact {
  path: string;
  contents: string;
}
function getArtifact(result: { artifacts: Artifact[] }, targetPath: string) {
  return result.artifacts.find(artifact => artifact.path === targetPath);
}

/** Fails naming `targetPath` when the result does not carry it. */
function requireArtifact(result: { artifacts: Artifact[] }, targetPath: string): Artifact {
  const artifact = getArtifact(result, targetPath);
  if (artifact === undefined) {
    throw new Error(`expected the result to carry ${targetPath}`);
  }
  return artifact;
}

function assertRestHelpers(t: ExecutionContext, result: { artifacts: Artifact[] }) {
  const restModel = getArtifact(result, 'rest.model.ts');
  const restUtil = getArtifact(result, 'rest.util.ts');

  t.truthy(restModel);
  t.truthy(restUtil);
  t.true(restModel?.contents?.includes('export interface CommonRequest'));
  t.true(restModel?.contents?.includes('export type HttpResourceOptionsUnion'));
  t.true(restUtil?.contents?.includes('export const requestFactory'));
  t.true(restUtil?.contents?.includes('export interface ZeroArgRequestFnVoid'));
}

function assertPetServiceArtifact(
  t: ExecutionContext,
  serviceSource: string | undefined,
) {
  t.truthy(serviceSource);
  t.true(serviceSource?.includes('export class PetRest {'));
  t.true(serviceSource?.includes('requestFactory.zeroArg<PetList>('));
  t.true(serviceSource?.includes('requestFactory<GetPetParams, Pet>('));
  t.true(serviceSource?.includes('requestFactory<UpdatePetParams, Pet>('));
  t.true(serviceSource?.includes('export interface GetPetParams {'));
  t.true(serviceSource?.includes('export interface UpdatePetParams {'));
  t.true(serviceSource?.includes('petId: PetId;'));
  t.true(serviceSource?.includes('includeHistory?: boolean;'));
  t.true(serviceSource?.includes('body: UpdatePetRequest;'));
  t.true(serviceSource?.includes('body: body,'));
}

test('normalize rejects path templates with unbalanced { } braces', async t => {
  // Before the normalize-stage guard, a path like `/pets/{id` would slip
  // through to the emit stage and silently produce a broken TypeScript
  // template (`url: `/pets/id`` with no `${encodeURIComponent(id)}`
  // expansion). The check rejects the spec instead.
  const err = await t.throwsAsync(
    async () => {
      await generate({
        inputPath: fixture('unbalanced-path-template.openapi.yaml'),
        emit: ['models', 'angular'],
      });
    },
    { instanceOf: GenerateError },
  );
  t.is(err?.code, 'E_UNSUPPORTED_SEMANTIC');
  t.regex(err?.message ?? '', /unbalanced.*'\{'/u);
  t.regex(err?.message ?? '', /\/pets\/\{id/u);
});

test('OpenAPI deprecated:true is mapped to @deprecated JSDoc on operations and properties', async t => {
  const result = await generate({
    inputPath: fixture('deprecated-fields.openapi.yaml'),
    emit: ['models', 'angular'],
  });

  const model = result.artifacts.find(a => a.path === 'model.ts');
  const service = result.artifacts.find(a => a.path === 'rest/pet.rest.ts');
  t.truthy(model);
  t.truthy(service);

  // Deprecated enum (top-level type alias) carries @deprecated JSDoc.
  t.regex(
    model?.contents ?? '',
    /\/\*\*[\s\S]*?Adoption state, legacy spelling\.[\s\S]*?@deprecated[\s\S]*?\*\/\s*export type LegacyPetStatus/u,
  );
  // Deprecated property inside an interface gets a per-property JSDoc.
  t.regex(
    model?.contents ?? '',
    /\/\*\*[\s\S]*?@deprecated[\s\S]*?\*\/\s*legacyTagId\?: number;/u,
  );
  // Non-deprecated property nearby does NOT pick up the marker — its
  // preceding line is the closing `*/` of the legacyTagId block, not a
  // standalone `@deprecated` JSDoc.
  const beforeTagIds = (model?.contents ?? '').match(
    /([^\n]*\n[^\n]*\n)\s*tagIds\?: number\[\];/u,
  );
  t.truthy(beforeTagIds, 'expected to find tagIds property');
  t.false(
    beforeTagIds?.[1]?.includes('@deprecated') ?? false,
    'tagIds must not be preceded by a @deprecated JSDoc',
  );

  // Deprecated operation: @deprecated lives in the JSDoc above the
  // service method, preserved alongside the merged summary+description.
  t.regex(
    service?.contents ?? '',
    /\/\*\*[\s\S]*?Retrieve a single pet[\s\S]*?@deprecated[\s\S]*?\*\/\s*readonly getPet/u,
  );
});

test('every generated artifact carries the version banner', async t => {
  // Forward-compat regression guard: pipeline emits `format!("{banner}{body}")`
  // for every artifact (models, rest.model.ts, rest.util.ts, per-tag service).
  // If any emit path ever materialises an artifact without threading the banner
  // through, this catches it before consumers see a banner-less file.
  const result = await generate({
    inputPath: fixture('petstore-rich.openapi.yaml'),
    emit: ['models', 'angular'],
  });

  t.true(result.artifacts.length >= 4, 'fixture should emit models + rest.* + service');
  for (const artifact of result.artifacts) {
    t.regex(
      artifact.contents,
      /^\/\/ Generated by openapi-ng v\d/,
      `${artifact.path} must start with the version banner`,
    );
  }
});

test.serial(
  'generate emits deterministic model and angular service artifacts for rich JSON and YAML fixtures',
  async t => {
    resetAngularConsumerGeneratedDir();

    await withTempDir(async outputPath => {
      const jsonResult = await generate({
        inputPath: fixture('petstore-rich.openapi.json'),
        outputPath: angularConsumerGeneratedDir,
        emit: ['models', 'angular'],
      });
      const yamlResult = await generate({
        inputPath: fixture('petstore-rich.openapi.yaml'),
        outputPath,
        emit: ['models', 'angular'],
      });

      t.deepEqual(jsonResult.diagnostics, []);
      t.deepEqual(yamlResult.diagnostics, []);

      t.deepEqual(
        { ...jsonResult.summary, normalizedSourcePath: undefined },
        { ...yamlResult.summary, normalizedSourcePath: undefined },
      );

      t.like(jsonResult, {
        summary: {
          specVersion: '3.0.3',
          title: 'Petstore Rich',
          pathCount: 2,
          operationCount: 3,
          schemaCount: 6,
        },
        artifacts: [
          { path: 'model.ts' },
          { path: 'rest.model.ts' },
          { path: 'rest.util.ts' },
          { path: 'rest.validate.ts' },
          { path: 'rest/pet.rest.ts' },
        ],
      });

      t.is(
        jsonResult.summary.normalizedSourcePath,
        'test/fixtures/petstore-rich.openapi.json',
      );
      t.is(
        yamlResult.summary.normalizedSourcePath,
        'test/fixtures/petstore-rich.openapi.yaml',
      );
      // Generated artifacts now carry a "// Source: <path>" banner line, so
      // JSON and YAML versions of the same spec produce intentionally
      // different bytes. Compare paths and verify that body (post-banner)
      // matches expectedModelSource for both surfaces.
      t.deepEqual(
        jsonResult.artifacts.map(a => a.path),
        yamlResult.artifacts.map(a => a.path),
      );
      t.is(stripBanner(jsonResult.artifacts[0]?.contents), expectedModelSource);
      t.is(stripBanner(yamlResult.artifacts[0]?.contents), expectedModelSource);
      assertRestHelpers(t, jsonResult);
      assertPetServiceArtifact(t, getArtifact(jsonResult, 'rest/pet.rest.ts')?.contents);
      t.true(fs.existsSync(path.join(angularConsumerGeneratedDir, 'model.ts')));
      t.true(fs.existsSync(path.join(angularConsumerGeneratedDir, 'rest.model.ts')));
      t.true(fs.existsSync(path.join(angularConsumerGeneratedDir, 'rest.util.ts')));
      t.true(
        fs.existsSync(path.join(angularConsumerGeneratedDir, 'rest', 'pet.rest.ts')),
      );
      t.is(
        stripBanner(
          fs.readFileSync(path.join(angularConsumerGeneratedDir, 'model.ts'), 'utf8'),
        ),
        expectedModelSource,
      );
      assertPetServiceArtifact(
        t,
        fs.readFileSync(
          path.join(angularConsumerGeneratedDir, 'rest', 'pet.rest.ts'),
          'utf8',
        ),
      );
    });
  },
);

test('generate defaults emit to models+angular when omitted, matching the CLI', async t => {
  // No `emit` field — the JS wrapper must apply the CLI's DEFAULT_EMIT
  // (`['models', 'angular']`) so the consumer receives the same artifact
  // set as `openapi-ng generate -i <fixture>`.
  const result = await generate({ inputPath: fixture('petstore-minimal.openapi.yaml') });

  t.true(
    result.artifacts.some(a => a.path === 'model.ts'),
    'default emit must include the models artifact',
  );
  t.true(
    result.artifacts.some(a => a.path.endsWith('.rest.ts')),
    'default emit must include an angular service artifact',
  );
});

test('generate produces models+angular when emit lists both targets', async t => {
  await withTempDir(async outputPath => {
    const result = await generate({
      inputPath: fixture('petstore-rich.openapi.yaml'),
      outputPath,
      emit: ['models', 'angular'],
    });

    t.deepEqual(result.diagnostics, []);
    t.deepEqual(artifactPaths(result), [
      'model.ts',
      'rest.model.ts',
      'rest.util.ts',
      'rest.validate.ts',
      'rest/pet.rest.ts',
    ]);
    t.is(stripBanner(result.artifacts[0]?.contents), expectedModelSource);
    assertRestHelpers(t, result);
    assertPetServiceArtifact(t, getArtifact(result, 'rest/pet.rest.ts')?.contents);
  });
});

test('generate rejects empty emit array as an invalid option', async t => {
  const error = await t.throwsAsync(async () => {
    await generate({
      inputPath: fixture('petstore-minimal.openapi.yaml'),
      emit: [],
    });
  });

  t.true(error instanceof GenerateError, 'thrown value must be a GenerateError instance');
  t.is((error as any)?.code, 'E_INVALID_OPTION');
  t.regex(error?.message ?? '', /emit/i);
});

test('generate auto-includes models when emit lists only angular, surfacing a non-fatal warning', async t => {
  const result = await generate({
    inputPath: fixture('petstore-minimal.openapi.yaml'),
    emit: ['angular'],
  });

  // Models artifact is present even though the caller did not list 'models'.
  t.true(result.artifacts.some(a => a.path === 'model.ts'));
  t.true(result.artifacts.some(a => a.path.startsWith('rest/')));

  // The pipeline surfaces the auto-include as an E_INVALID_OPTION warning
  // so consumers can see (with --verbose, or by inspecting diagnostics)
  // that their emit list was widened.
  const warning = result.diagnostics.find(d => d.code === 'E_INVALID_OPTION');
  t.truthy(warning, 'expected an E_INVALID_OPTION warning');
  t.is(warning?.severity, 'warning');
  t.regex(warning?.message ?? '', /Auto-included 'models'/);
  t.regex(warning?.message ?? '', /'angular'/);
});

test('generate rejects unknown option keys with E_INVALID_OPTION instead of silently ignoring them', async t => {
  const error = await t.throwsAsync(async () => {
    await generate({
      inputPath: fixture('petstore-minimal.openapi.yaml'),
      emit: [...DEFAULT_EMIT],
      // typo: lowercase `inputpath` and an unrecognised `artifacts` option
      inputpath: 'oops',
      artifacts: 'metadata',
    } as any);
  });

  t.true(error instanceof GenerateError, 'thrown value must be a GenerateError instance');
  t.is((error as any)?.code, 'E_INVALID_OPTION');
  t.regex(error?.message ?? '', /inputpath/);
  t.regex(error?.message ?? '', /artifacts/);
});

test('generate rejects non-array emit with a typed E_INVALID_OPTION (subcode shape) before crossing the NAPI boundary', async t => {
  const error = await t.throwsAsync(async () => {
    await generate({
      inputPath: fixture('petstore-minimal.openapi.yaml'),
      outputPath: 'unused',
      // typo: string instead of EmitTarget[]
      emit: 'angular',
    } as any);
  });

  t.true(error instanceof GenerateError, 'thrown value must be a GenerateError instance');
  t.is((error as any)?.code, 'E_INVALID_OPTION');
  t.is((error as any)?.subcode, 'shape');
  t.regex(error?.message ?? '', /emit must be an array/);
});

test('generate rejects non-array mappedTypes with E_INVALID_OPTION (subcode shape) before crossing the NAPI boundary', async t => {
  const error = await t.throwsAsync(async () => {
    await generate({
      inputPath: fixture('petstore-minimal.openapi.yaml'),
      outputPath: 'unused',
      emit: [...DEFAULT_EMIT],
      // typo: scalar instead of MappedType[]
      mappedTypes: 'foo',
    } as any);
  });

  t.true(error instanceof GenerateError, 'thrown value must be a GenerateError instance');
  t.is((error as any)?.code, 'E_INVALID_OPTION');
  t.is((error as any)?.subcode, 'shape');
  t.regex(error?.message ?? '', /mappedTypes must be an array/);
});

test('generate rejects emit entries not in EmitTarget union', async t => {
  const err = await t.throwsAsync(
    async () => {
      await generate({
        inputPath: 'x.yaml',
        emit: ['Models'] as any, // capitalized → invalid
      });
    },
    { instanceOf: GenerateError },
  );
  t.is(err?.code, 'E_INVALID_OPTION');
  t.is(err?.subcode, 'shape');
  t.regex(err?.message ?? '', /'Models'/);
});

test('generate rejects non-string inputPath', async t => {
  // Cast to any: TypeScript would catch this, but a JS consumer wouldn't.
  const err = await t.throwsAsync(
    async () => {
      await generate({ inputPath: 123 as any, emit: ['models'] });
    },
    { instanceOf: GenerateError },
  );
  t.is(err?.code, 'E_INVALID_OPTION');
  t.is(err?.subcode, 'shape');
  t.regex(err?.message ?? '', /inputPath/);
});

test('generate rejects malformed mappedTypes entries', async t => {
  const err = await t.throwsAsync(
    async () => {
      await generate({
        inputPath: 'x.yaml',
        emit: ['models'],
        mappedTypes: [{ schema: 'X' } as any], // missing import + type
      });
    },
    { instanceOf: GenerateError },
  );
  t.is(err?.code, 'E_INVALID_OPTION');
  t.is(err?.subcode, 'shape');
});

test('generate rejects when neither inputPath nor inputContents is set', async t => {
  const err = await t.throwsAsync(async () => {
    await generate({ emit: ['models'] } as any);
  });
  t.true(err instanceof GenerateError);
  t.is((err as any).code, 'E_INVALID_OPTION');
  t.is((err as any).subcode, 'shape');
  t.true((err as any).message.includes('exactly one'));
});

test('generate rejects when both inputPath and inputContents are set', async t => {
  const err = await t.throwsAsync(async () => {
    await generate({
      inputPath: 'spec.yaml',
      inputContents: 'openapi: 3.0.3\n',
      displayPath: 'inline',
      emit: ['models'],
    } as any);
  });
  t.is((err as any).code, 'E_INVALID_OPTION');
  t.is((err as any).subcode, 'shape');
});

test('generate rejects inputContents without displayPath', async t => {
  const err = await t.throwsAsync(async () => {
    await generate({
      inputContents: 'openapi: 3.0.3\n',
      emit: ['models'],
    } as any);
  });
  t.is((err as any).code, 'E_INVALID_OPTION');
  t.is((err as any).subcode, 'shape');
  t.true((err as any).message.includes('displayPath'));
});

test('generate rejects inputFormat with inputPath', async t => {
  const err = await t.throwsAsync(async () => {
    await generate({
      inputPath: 'spec.yaml',
      inputFormat: 'json',
      emit: ['models'],
    } as any);
  });
  t.is((err as any).code, 'E_INVALID_OPTION');
  t.is((err as any).subcode, 'shape');
});

test('generate accepts inputContents with displayPath and yields a result', async t => {
  const yaml = 'openapi: 3.0.3\ninfo: { title: Inline Pkg, version: 1.0.0 }\npaths: {}\n';
  const result = await generate({
    inputContents: yaml,
    displayPath: 'https://example.com/spec.yaml',
    inputFormat: 'yaml',
    emit: ['models'],
  } as any);
  t.is(result.summary.title, 'Inline Pkg');
  t.is(result.summary.normalizedSourcePath, 'https://example.com/spec.yaml');
});

test('generate fails when discriminator property is absent on a oneOf member', async t => {
  const err = await t.throwsAsync(
    async () => {
      await generate({
        inputPath: fixture('discriminator-missing-property.openapi.yaml'),
        emit: ['models'],
      });
    },
    { instanceOf: GenerateError },
  );
  t.is(err?.code, 'E_POLICY_VIOLATION');
  t.is(err?.subcode, 'missing-discriminator-property');
  t.regex(err?.message ?? '', /Cat/);
});

test('generate rejects empty-string outputPath; in-memory mode requires omitting the field', async t => {
  const error = await t.throwsAsync(async () => {
    await generate({
      inputPath: fixture('petstore-minimal.openapi.yaml'),
      outputPath: '',
      emit: [...DEFAULT_EMIT],
    });
  });

  t.truthy(error);
  t.is((error as any)?.code, 'E_INVALID_OPTION');
  t.regex(error?.message ?? '', /outputPath must be a non-empty path/);
});

test('generate returns artifact contents and writes the same bytes to disk', async t => {
  await withTempDir(async outputPath => {
    const result = await generate({
      inputPath: fixture('petstore-rich.openapi.yaml'),
      outputPath,
      emit: [...DEFAULT_EMIT],
    });

    t.true(result.artifacts.length > 0);
    for (const artifact of result.artifacts) {
      t.is(typeof artifact.contents, 'string');
      t.true(artifact.contents.length > 0, `${artifact.path} contents must be non-empty`);
    }
    // Files were still written to disk.
    t.true(fs.existsSync(path.join(outputPath, 'model.ts')));
    const modelArtifact = requireArtifact(result, 'model.ts');
    t.is(
      fs.readFileSync(path.join(outputPath, 'model.ts'), 'utf8'),
      modelArtifact?.contents,
    );
  });
});

test('generate exposes flattened request interfaces and operation-object APIs in the service artifact', async t => {
  await withTempDir(async outputPath => {
    const result = await generate({
      inputPath: fixture('petstore-rich.openapi.yaml'),
      outputPath,
      emit: [...DEFAULT_EMIT],
    });

    t.deepEqual(result.diagnostics, []);
    const serviceArtifact = getArtifact(result, 'rest/pet.rest.ts');

    t.truthy(serviceArtifact);
    assertPetServiceArtifact(t, serviceArtifact?.contents);
    t.false(serviceArtifact?.contents?.includes('#http'));
    t.false(serviceArtifact?.contents?.includes('HttpClient'));
    t.true(serviceArtifact?.contents?.includes('requestFactory.zeroArg<PetList>('));
    t.true(serviceArtifact?.contents?.includes('requestFactory<GetPetParams, Pet>('));
    t.true(serviceArtifact?.contents?.includes('requestFactory<UpdatePetParams, Pet>('));
  });
});

test('generate surfaces the bounded option contract through the node api', async t => {
  await withTempDir(async outputPath => {
    const result = await generate({
      inputPath: fixture('petstore-rich.openapi.yaml'),
      outputPath,
      emit: [...FULL_EMIT],
      mappedTypes: [
        {
          schema: 'PetId',
          import: '@demo/native-types',
          type: 'PetIdentifier',
        },
      ],
    });

    t.deepEqual(result.diagnostics, []);
  });
});

test.serial(
  'generate emits discriminated-union model that narrows correctly in a consumer project',
  async t => {
    resetAngularConsumerGeneratedDir();

    await generate({
      inputPath: fixture('discriminated-union.openapi.yaml'),
      outputPath: angularConsumerGeneratedDir,
      emit: [...DEFAULT_EMIT],
    });

    execFileSync(
      process.execPath,
      [
        path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
        '-p',
        path.join(__dirname, 'angular-consumer', 'tsconfig.discriminator.json'),
      ],
      {
        cwd: path.join(__dirname, 'angular-consumer'),
        stdio: 'pipe',
      },
    );
    t.pass('tsc type-checked discriminated-union narrowing successfully');
  },
);

test.serial(
  'generate emits service helper typings that type-check in a consumer project',
  async t => {
    resetAngularConsumerGeneratedDir();

    await generate({
      inputPath: fixture('petstore-rich.openapi.json'),
      outputPath: angularConsumerGeneratedDir,
      emit: [...DEFAULT_EMIT],
    });

    execFileSync(
      process.execPath,
      [
        path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
        '-p',
        path.join(__dirname, 'angular-consumer', 'tsconfig.service.json'),
      ],
      {
        cwd: path.join(__dirname, 'angular-consumer'),
        stdio: 'pipe',
      },
    );
    t.pass('tsc type-checked generated service artifact successfully');
  },
);

test.serial(
  'generate emits validateRest typings that type-check in a consumer project',
  async t => {
    resetAngularConsumerGeneratedDir();

    await generate({
      inputPath: fixture('petstore-rich.openapi.json'),
      outputPath: angularConsumerGeneratedDir,
      emit: [...DEFAULT_EMIT],
    });

    execFileSync(
      process.execPath,
      [
        path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
        '-p',
        path.join(__dirname, 'angular-consumer', 'tsconfig.validate.json'),
      ],
      {
        cwd: path.join(__dirname, 'angular-consumer'),
        stdio: 'pipe',
      },
    );
    t.pass('tsc type-checked generated validateRest surface successfully');
  },
);

// Type-surface gate for `EmitTarget`. The proof file destructures the
// runtime `EmitTarget` and asserts assignability between its named
// properties and the published `EmitTarget` type, compiled under
// `isolatedModules`. If the published `index.d.ts` ever regresses to a
// `const enum` form, isolatedModules' single-file transpilation rejects
// the import and this gate fails.
test('public EmitTarget surface compiles under isolatedModules', t => {
  execFileSync(
    process.execPath,
    [
      path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
      '-p',
      path.join(__dirname, 'angular-consumer', 'tsconfig.emit-target.json'),
    ],
    {
      cwd: path.join(__dirname, 'angular-consumer'),
      stdio: 'pipe',
    },
  );
  t.pass('tsc type-checked EmitTarget public surface under isolatedModules');
});

test.serial(
  'generate emits oneOf/anyOf composition models that type-check in a consumer project',
  async t => {
    resetAngularConsumerGeneratedDir();

    await generate({
      inputPath: fixture('oneof-anyof-composition.openapi.yaml'),
      outputPath: angularConsumerGeneratedDir,
      emit: [...DEFAULT_EMIT],
    });

    execFileSync(
      process.execPath,
      [
        path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
        '-p',
        path.join(__dirname, 'angular-consumer', 'tsconfig.consumer.json'),
      ],
      {
        cwd: path.join(__dirname, 'angular-consumer'),
        stdio: 'pipe',
      },
    );
    t.pass('tsc type-checked generated oneOf/anyOf composition output successfully');
  },
);

// Bulk-spec compile gate: bench-large emits 30 entity models and 30
// service files referencing them. The all-snapshots compile gate in
// generate.snapshot.spec.ts covers the snapshot bytes; this dedicated
// gate exercises a freshly-generated output against the real Angular
// consumer's tsconfig, so a regression in bulk emit surfaces as a
// targeted failure (not a snapshot diff buried in a 30-file blob).
test.serial(
  'generate emits bulk-spec output that type-checks under an Angular consumer (bench-large)',
  async t => {
    resetAngularConsumerGeneratedDir();

    await generate({
      inputPath: fixture('bench-large.openapi.yaml'),
      outputPath: angularConsumerGeneratedDir,
      emit: [...DEFAULT_EMIT],
    });

    execFileSync(
      process.execPath,
      [
        path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
        '-p',
        path.join(__dirname, 'angular-consumer', 'tsconfig.bench-large.json'),
      ],
      {
        cwd: path.join(__dirname, 'angular-consumer'),
        stdio: 'pipe',
      },
    );
    t.pass('tsc type-checked bulk-spec (bench-large) generated output successfully');
  },
);

// Negative-compile fixture: asserts that tsc FAILS when assigning a Dog to a
// Cat-typed slot. If this test ever starts passing (tsc exits 0), it means the
// tagged union has collapsed to `any` or similar — a type-soundness regression.
test.serial(
  'negative-proof tsconfig fails to compile (type-soundness regression detector)',
  async t => {
    resetAngularConsumerGeneratedDir();

    await generate({
      inputPath: fixture('discriminated-union.openapi.yaml'),
      outputPath: angularConsumerGeneratedDir,
      emit: [...DEFAULT_EMIT],
    });

    const result = spawnSync(
      process.execPath,
      [
        path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
        '-p',
        path.join(__dirname, 'angular-consumer', 'tsconfig.negative.json'),
      ],
      {
        cwd: path.join(__dirname, 'angular-consumer'),
        encoding: 'utf8',
      },
    );

    const stdout = (result.stdout ?? '') + (result.stderr ?? '');

    // Must fail — otherwise types have become too permissive (e.g. collapsed to `any`).
    t.not(result.status, 0, `expected tsc to fail but it succeeded; output:\n${stdout}`);
    // The specific error must be TS2322 (type assignability), not e.g. TS2304 (cannot find name).
    t.regex(stdout, /TS2322/, `expected TS2322 type-mismatch error; output:\n${stdout}`);
  },
);

// Compile gate for the request-body (multipart + urlencoded) and
// non-JSON response (Blob / string / ArrayBuffer) surfaces. The proof
// file (src/form-non-json-proof.ts) asserts call-site typing on each
// service and pins the carrier type of `observable` / `resource` via
// expectType<>. Generated from a combined fixture that also exercises
// the user-facing `responseTypeMapping` knob (octet-stream → ArrayBuffer).
// A regression that widens a binary field to `any`, drops the response
// generic, or fails to honour the mapping fails here under tsc --noEmit.
test.serial(
  'generate emits form-body and non-JSON response typings that type-check in a consumer project',
  async t => {
    resetAngularConsumerGeneratedDir();

    await generate({
      inputPath: fixture('consumer-forms-and-non-json.openapi.yaml'),
      outputPath: angularConsumerGeneratedDir,
      emit: [...DEFAULT_EMIT],
      responseTypeMapping: [
        { contentType: 'application/octet-stream', responseType: 'arrayBuffer' },
      ],
    });

    execFileSync(
      process.execPath,
      [
        path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
        '-p',
        path.join(__dirname, 'angular-consumer', 'tsconfig.form-non-json.json'),
      ],
      {
        cwd: path.join(__dirname, 'angular-consumer'),
        stdio: 'pipe',
      },
    );
    t.pass('tsc type-checked form-body + non-JSON response artifacts successfully');
  },
);

// Negative-compile fixture for the multipart binary-field surface:
// asserts that tsc FAILS when assigning a plain `string` to a
// `Blob | File` slot in the generated `UpdatePetAvatarParams`. If this
// test starts passing (tsc exits 0), the binary field has widened to
// `any`/`unknown` or to `string`-permissive — a type-soundness
// regression that would silently let callers ship non-binary payloads
// down the multipart path.
test.serial(
  'negative-proof tsconfig fails to compile when a string is passed to a binary multipart field',
  async t => {
    resetAngularConsumerGeneratedDir();

    await generate({
      inputPath: fixture('consumer-forms-and-non-json.openapi.yaml'),
      outputPath: angularConsumerGeneratedDir,
      emit: [...DEFAULT_EMIT],
      responseTypeMapping: [
        { contentType: 'application/octet-stream', responseType: 'arrayBuffer' },
      ],
    });

    const result = spawnSync(
      process.execPath,
      [
        path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
        '-p',
        path.join(__dirname, 'angular-consumer', 'tsconfig.negative-binary-field.json'),
      ],
      {
        cwd: path.join(__dirname, 'angular-consumer'),
        encoding: 'utf8',
      },
    );

    const stdout = (result.stdout ?? '') + (result.stderr ?? '');

    // Must fail — otherwise the binary field has widened (e.g. to `string`/`any`).
    t.not(result.status, 0, `expected tsc to fail but it succeeded; output:\n${stdout}`);
    // The specific error must be TS2322 (type assignability), not e.g. TS2304 (cannot find name).
    t.regex(stdout, /TS2322/, `expected TS2322 type-mismatch error; output:\n${stdout}`);
  },
);

test.serial(
  'negative-proof tsconfig fails to compile when validateRest request returns a mismatched shape',
  async t => {
    resetAngularConsumerGeneratedDir();

    await generate({
      inputPath: fixture('petstore-rich.openapi.json'),
      outputPath: angularConsumerGeneratedDir,
      emit: [...DEFAULT_EMIT],
    });

    const result = spawnSync(
      process.execPath,
      [
        path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
        '-p',
        path.join(__dirname, 'angular-consumer', 'tsconfig.negative-validate.json'),
      ],
      {
        cwd: path.join(__dirname, 'angular-consumer'),
        encoding: 'utf8',
      },
    );

    const stdout = (result.stdout ?? '') + (result.stderr ?? '');

    // Must fail — otherwise the request callback's return type has widened.
    t.not(result.status, 0, `expected tsc to fail but it succeeded; output:\n${stdout}`);
    // The error must be a type-mismatch on the request shape (TS2322 type
    // assignability or TS2739 missing-properties), not e.g. TS2304 (cannot
    // find name) — that would mean the proof file is broken, not that the
    // typing rejected the mismatch.
    t.regex(
      stdout,
      /TS2322|TS2739/,
      `expected TS2322/TS2739 type-mismatch error; output:\n${stdout}`,
    );
  },
);

test.serial(
  'negative-proof tsconfig fails to compile when validateRest onSuccess reads a non-existent response field',
  async t => {
    resetAngularConsumerGeneratedDir();

    await generate({
      inputPath: fixture('petstore-rich.openapi.json'),
      outputPath: angularConsumerGeneratedDir,
      emit: [...DEFAULT_EMIT],
    });

    const result = spawnSync(
      process.execPath,
      [
        path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
        '-p',
        path.join(
          __dirname,
          'angular-consumer',
          'tsconfig.negative-validate-response.json',
        ),
      ],
      {
        cwd: path.join(__dirname, 'angular-consumer'),
        encoding: 'utf8',
      },
    );

    const stdout = (result.stdout ?? '') + (result.stderr ?? '');

    // Must fail — otherwise the onSuccess result type has widened.
    t.not(result.status, 0, `expected tsc to fail but it succeeded; output:\n${stdout}`);
    // The error must be TS2339 (property does not exist), not e.g. TS2304
    // (cannot find name) — that would mean the proof file is broken.
    t.regex(
      stdout,
      /TS2339/,
      `expected TS2339 property-access error; output:\n${stdout}`,
    );
  },
);

test.serial(
  'negative-proof tsconfig fails to compile when validateRest debounce is not a DebounceTimer',
  async t => {
    resetAngularConsumerGeneratedDir();

    await generate({
      inputPath: fixture('petstore-rich.openapi.json'),
      outputPath: angularConsumerGeneratedDir,
      emit: [...DEFAULT_EMIT],
    });

    const result = spawnSync(
      process.execPath,
      [
        path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
        '-p',
        path.join(
          __dirname,
          'angular-consumer',
          'tsconfig.negative-validate-debounce.json',
        ),
      ],
      {
        cwd: path.join(__dirname, 'angular-consumer'),
        encoding: 'utf8',
      },
    );

    const stdout = (result.stdout ?? '') + (result.stderr ?? '');

    // Must fail — otherwise `debounce` is no longer picked off Angular's
    // AsyncValidatorOptions as a real DebounceTimer (e.g. it widened to `any`,
    // or the Extract<keyof …> pick silently resolved to an index signature).
    t.not(result.status, 0, `expected tsc to fail but it succeeded; output:\n${stdout}`);
    t.regex(stdout, /TS2322/, `expected TS2322 type-mismatch error; output:\n${stdout}`);
  },
);

test('generate maps a targeted schema to an imported external type without changing unrelated model symbols', async t => {
  await withTempDir(async outputPath => {
    const result = await generate({
      inputPath: fixture('petstore-rich.openapi.yaml'),
      outputPath,
      emit: [...DEFAULT_EMIT],

      mappedTypes: [
        {
          schema: 'PetId',
          import: '@demo/native-types',
          type: 'PetIdentifier',
        },
      ],
    });

    const modelArtifact = requireArtifact(result, 'model.ts');

    t.truthy(modelArtifact);
    const serviceArtifact = getArtifact(result, 'rest/pet.rest.ts');

    t.truthy(serviceArtifact);
    t.true(
      modelArtifact?.contents?.includes(
        "import type { PetIdentifier } from '@demo/native-types';",
      ),
    );
    t.false(modelArtifact?.contents?.includes('export type PetId = string;'));
    t.true(modelArtifact?.contents?.includes('export type PetStatus ='));
    t.true(
      serviceArtifact?.contents?.includes(
        "import type { Pet, PetId, PetList, UpdatePetRequest } from '../model';",
      ),
    );
    t.true(serviceArtifact?.contents?.includes('  petId: PetId;'));
  });
});

test('generate encodes oneOf/anyOf composition as focused public contract fragments', async t => {
  await withTempDir(async outputPath => {
    const result = await generate({
      inputPath: fixture('oneof-anyof-composition.openapi.yaml'),
      outputPath,
      emit: [...DEFAULT_EMIT],
    });

    // `format-dropped` warnings are orthogonal to this test's focus on
    // composition emit; the snapshot suite pins the full warning list.
    t.deepEqual(
      result.diagnostics.filter(d => d.subcode !== 'format-dropped'),
      [],
    );

    const modelArtifact = requireArtifact(result, 'model.ts');
    const serviceArtifact = getArtifact(result, 'rest/adoption-request.rest.ts');

    t.truthy(modelArtifact);
    t.truthy(serviceArtifact);
    t.deepEqual(artifactPaths(result), [
      'model.ts',
      'rest.model.ts',
      'rest.util.ts',
      'rest.validate.ts',
      'rest/adoption-request.rest.ts',
      'rest/pet.rest.ts',
    ]);
    t.true(modelArtifact?.contents?.includes('export type PetUnion = Cat | Dog;'));
    t.true(modelArtifact?.contents?.includes('export type PetUnionList = PetUnion[];'));
    t.true(modelArtifact?.contents?.includes('  preferredPet?: PetUnion;'));
    t.true(modelArtifact?.contents?.includes('  contact: ContactEmail | ContactPhone;'));
    t.true(modelArtifact?.contents?.includes('  notes?: string;'));
    t.true(modelArtifact?.contents?.includes('  referralCode?: string | null;'));
    t.true(modelArtifact?.contents?.includes('  matchedPet?: PetUnion;'));
    t.true(modelArtifact?.contents?.includes('  reviewerNote?: string | null;'));
    t.true(
      serviceArtifact?.contents?.includes(
        'requestFactory<CreateAdoptionRequestParams, AdoptionDecision>(',
      ),
    );
  });
});

test('generate keeps mapped-type assertions explicit alongside composition contract coverage', async t => {
  await withTempDir(async outputPath => {
    const result = await generate({
      inputPath: fixture('oneof-anyof-composition.openapi.yaml'),
      outputPath,
      emit: [...DEFAULT_EMIT],

      mappedTypes: [
        {
          schema: 'Cat',
          import: '@demo/composition-types',
          type: 'ExternalCat',
        },
      ],
    });

    const modelArtifact = requireArtifact(result, 'model.ts');

    t.truthy(modelArtifact);
    t.true(
      modelArtifact?.contents?.includes(
        "import type { ExternalCat } from '@demo/composition-types';",
      ),
    );
    t.true(modelArtifact?.contents?.includes('export type PetUnion = Cat | Dog;'));
    t.true(modelArtifact?.contents?.includes('export type Cat = ExternalCat;'));
    t.false(modelArtifact?.contents?.includes('  lives: number;'));
  });
});

test('generate emits a re-export for mapped types whose binding name equals the schema name', async t => {
  await withTempDir(async outputPath => {
    const result = await generate({
      inputPath: fixture('oneof-anyof-composition.openapi.yaml'),
      outputPath,
      emit: [...DEFAULT_EMIT],
      mappedTypes: [
        // alias=Cat matches the schema, so `import type { ExternalCat
        // as Cat }` + `export type Cat = Cat;` would collide. The
        // emitter must collapse to a single `export type { ... } from
        // '...'` re-export.
        {
          schema: 'Cat',
          import: '@demo/composition-types',
          type: 'ExternalCat',
          alias: 'Cat',
        },
      ],
    });

    const modelArtifact = requireArtifact(result, 'model.ts');
    t.truthy(modelArtifact);
    t.true(
      modelArtifact?.contents?.includes(
        "export type { ExternalCat as Cat } from '@demo/composition-types';",
      ),
    );
    t.false(
      modelArtifact?.contents?.includes('export type Cat = Cat;'),
      'self-alias case must not emit the broken placeholder',
    );
    t.false(
      modelArtifact?.contents?.includes('import type { ExternalCat as Cat }'),
      'self-alias case must not emit a separate import-type line',
    );
  });
});

test('generate emits a bare re-export when schema name equals imported type name', async t => {
  await withTempDir(async outputPath => {
    const result = await generate({
      inputPath: fixture('oneof-anyof-composition.openapi.yaml'),
      outputPath,
      emit: [...DEFAULT_EMIT],
      mappedTypes: [
        {
          schema: 'Cat',
          import: '@demo/composition-types',
          type: 'Cat',
        },
      ],
    });

    const modelArtifact = requireArtifact(result, 'model.ts');
    t.truthy(modelArtifact);
    t.true(
      modelArtifact?.contents?.includes(
        "export type { Cat } from '@demo/composition-types';",
      ),
    );
    t.false(
      modelArtifact?.contents?.includes(' as Cat'),
      'no rename needed when names match',
    );
  });
});

test('generate encodes allOf composition as an intersection contract with nullable-vs-optional fragments', async t => {
  await withTempDir(async outputPath => {
    const result = await generate({
      inputPath: fixture('allof-composition.openapi.yaml'),
      outputPath,
      emit: [...DEFAULT_EMIT],
    });

    // `format-dropped` warnings are orthogonal to this test's focus on
    // intersection emit; the snapshot suite pins the full warning list.
    t.deepEqual(
      result.diagnostics.filter(d => d.subcode !== 'format-dropped'),
      [],
    );

    const modelArtifact = requireArtifact(result, 'model.ts');
    const serviceArtifact = getArtifact(result, 'rest/adopter.rest.ts');

    t.truthy(modelArtifact);
    t.truthy(serviceArtifact);
    t.deepEqual(artifactPaths(result), [
      'model.ts',
      'rest.model.ts',
      'rest.util.ts',
      'rest.validate.ts',
      'rest/adopter.rest.ts',
    ]);
    t.true(
      modelArtifact?.contents?.includes(
        'export type AdopterProfile = AuditFields & ContactFields & {',
      ),
    );
    t.true(modelArtifact?.contents?.includes('  id: string;'));
    t.true(modelArtifact?.contents?.includes('  name: string;'));
    t.true(modelArtifact?.contents?.includes('  nickname?: string | null;'));
    t.true(modelArtifact?.contents?.includes('  archivedAt?: string | null;'));
    t.true(modelArtifact?.contents?.includes('  phone?: string;'));
    t.true(
      serviceArtifact?.contents?.includes(
        'requestFactory<GetAdopterProfileParams, AdopterProfile>(',
      ),
    );
  });
});

test('generate collapses single-entry oneOf/anyOf/allOf wrappers instead of emitting redundant composition syntax', async t => {
  await withTempDir(async outputPath => {
    const result = await generate({
      inputPath: fixture('single-entry-composition.openapi.yaml'),
      outputPath,
      emit: [...DEFAULT_EMIT],
    });

    t.deepEqual(result.diagnostics, []);

    const modelArtifact = requireArtifact(result, 'model.ts');

    t.truthy(modelArtifact);
    t.true(modelArtifact?.contents?.includes('export type AnimalView = AnimalBase;'));
    t.true(modelArtifact?.contents?.includes('export type AnimalDraft = AnimalBase;'));
    t.true(modelArtifact?.contents?.includes('export type ContactPreference = string;'));
    t.false(modelArtifact?.contents?.includes('AnimalBase |'));
    t.false(modelArtifact?.contents?.includes('AnimalBase &'));
    t.false(modelArtifact?.contents?.includes('ContactPreference |'));
    t.true(modelArtifact?.contents?.includes('  nickname?: string | null;'));
  });
});

test('generate emits Record-based contracts for typed additionalProperties object maps', async t => {
  await withTempDir(async outputPath => {
    const result = await generate({
      inputPath: fixture('additional-properties.openapi.yaml'),
      outputPath,
      emit: [...DEFAULT_EMIT],
    });

    t.deepEqual(result.diagnostics, []);

    const modelArtifact = requireArtifact(result, 'model.ts');
    const serviceArtifact = getArtifact(result, 'rest/pet.rest.ts');

    t.truthy(modelArtifact);
    t.truthy(serviceArtifact);
    t.true(modelArtifact?.contents?.includes('  petsByBreed: Record<string, Pet[]>;'));
    t.true(
      modelArtifact?.contents?.includes(
        'export type PetMetadataByTag = Record<string, PetMetadata>;',
      ),
    );
    t.true(serviceArtifact?.contents?.includes('requestFactory.zeroArg<PetCatalog>('));
  });
});

test('unsupported semantic fixture reports normalize-stage additionalProperties boundary instead of composition rejection', async t => {
  await withTempDir(async outputPath => {
    const error = await t.throwsAsync(async () => {
      await generate({
        inputPath: fixture('unsupported-semantic.openapi.yaml'),
        outputPath,
        emit: [...DEFAULT_EMIT],
      });
    });

    t.truthy(error);
    t.true(error instanceof GenerateError);
    t.is((error as any)?.code, unsupportedSemanticDiagnostic.code);
    t.is((error as any)?.path, unsupportedSemanticDiagnostic.path);
    t.regex(error?.message ?? '', /additionalProperties/i);
    t.notRegex(error?.message ?? '', /\ballOf\b/i);
    // Warnings live on `error.warnings`; the fatal sits at top level.
    t.deepEqual((error as any)?.warnings, []);
  });
});

test('generate rejects malformed fixture with stable fatal input diagnostic metadata', async t => {
  await withTempDir(async outputPath => {
    const error = await t.throwsAsync(async () => {
      await generate({
        inputPath: fixture('malformed.yaml'),
        outputPath,
        emit: [...DEFAULT_EMIT],
      });
    });

    t.truthy(error);
    t.true(error instanceof GenerateError);
    t.is((error as any)?.code, 'E_INPUT_INVALID');
    t.true((error as any)?.path.endsWith('test/fixtures/malformed.yaml'));
  });
});

test('generate rejects unsupported-root fixture with stable input-stage shape diagnostics', async t => {
  await withTempDir(async outputPath => {
    const error = await t.throwsAsync(async () => {
      await generate({
        inputPath: fixture('unsupported-root.yaml'),
        outputPath,
        emit: [...DEFAULT_EMIT],
      });
    });

    t.truthy(error);
    t.true(error instanceof GenerateError);
    t.is((error as any)?.code, unsupportedRootDiagnostic.code);
    t.is(error?.message, unsupportedRootDiagnostic.message);
    t.is((error as any)?.path, unsupportedRootDiagnostic.path);
  });
});

test('generate produces byte-identical output across repeated calls (determinism)', async t => {
  // README guarantees deterministic output: "same input always produces
  // identical output". Run each fixture three times and assert byte-level
  // equality on the full result (summary + diagnostics + artifact contents
  // including banner).
  const fixtures = ['petstore-rich.openapi.yaml', 'bench-large.openapi.yaml'];
  for (const name of fixtures) {
    // Sequential: state leaking from one run into the next is only
    // observable in order. Concurrency has its own test below.
    const first = await generate({ inputPath: fixture(name), emit: [...DEFAULT_EMIT] });
    const second = await generate({ inputPath: fixture(name), emit: [...DEFAULT_EMIT] });
    const third = await generate({ inputPath: fixture(name), emit: [...DEFAULT_EMIT] });
    t.deepEqual(first, second, `${name}: run 1 vs run 2 must be byte-identical`);
    t.deepEqual(second, third, `${name}: run 2 vs run 3 must be byte-identical`);
  }
});

test('generate rejects schemas nested deeper than MAX_NORMALIZE_DEPTH', async t => {
  // Pathological inline-allOf nesting (40 levels) trips the depth guard
  // at level 32 — well below the serde recursion limit (~60), so this
  // exercises the normalize-side guard rather than the YAML/JSON
  // decoder's own protection. The error must surface as a typed
  // GenerateError carrying E_UNSUPPORTED_SEMANTIC (no new subcode), with
  // a message mentioning "nesting" and "exceeds" so consumers can
  // recognise the bound rather than treating it as a generic schema
  // shape failure.
  const err = await t.throwsAsync(
    async () => {
      await generate({
        inputPath: path.join(
          __dirname,
          '../test/fixtures/deep-nested-allof.openapi.yaml',
        ),
        emit: ['models'],
      });
    },
    { instanceOf: GenerateError },
  );
  t.is(err?.code, 'E_UNSUPPORTED_SEMANTIC');
  t.regex(err?.message ?? '', /nesting.*exceeds/i);
});

test('generate wraps Rust panic into E_UNEXPECTED GenerateError', async t => {
  // Triggered by the cfg-test-only `inputPath: "__panic_for_test__"` sentinel.
  const err = await t.throwsAsync(
    async () => {
      await generate({
        inputPath: '__panic_for_test__',
        emit: ['models'],
      });
    },
    { instanceOf: GenerateError },
  );
  t.is(err?.code, 'E_UNEXPECTED');
  // wasm cannot unwind, so a panic traps as `unreachable` and the payload is
  // lost; only the native binding carries the panic text through.
  if (process.env.NAPI_RS_FORCE_WASI !== 'true') {
    t.regex(err?.message ?? '', /unexpected.*panic/i);
  }
});

test('GenerateError is a real class so consumers can guard with instanceof', async t => {
  const error = await t.throwsAsync(async () => {
    await generate({
      inputPath: fixture('petstore-minimal.openapi.yaml'),
      // emit is required — the missing field surfaces as a fatal
      // option-resolution error.
      emit: [],
    });
  });

  t.true(error instanceof GenerateError, 'thrown value must be a GenerateError instance');
  t.is((error as any).code, 'E_INVALID_OPTION');
  t.is(typeof (error as any).message, 'string');
  t.true(Array.isArray((error as any).warnings));
});

test('GenerateError carries pre-fatal warnings on error.warnings', async t => {
  // The warning-then-fatal fixture trips a cookie-parameter warning on
  // operation /a (normalize keeps going past warnings), then a fatal on
  // operation /b (unsupported parameter location). Asserts the NAPI
  // boundary enriches the thrown error with both surfaces: the fatal at
  // top-level and the pre-fatal warning on `warnings[]`.
  const error = await t.throwsAsync(async () => {
    await generate({
      inputPath: fixture('warning-then-fatal.openapi.yaml'),
      emit: ['models', 'angular'],
    });
  });

  t.true(error instanceof GenerateError);
  t.is((error as any).code, 'E_UNSUPPORTED_SEMANTIC');
  t.regex(error?.message ?? '', /bogus_location/);

  const warnings = (error as any).warnings as Array<{
    code: string;
    severity: string;
    message: string;
    path: string;
  }>;
  t.true(Array.isArray(warnings));
  t.is(warnings.length, 1, 'cookie param should produce exactly one pre-fatal warning');
  t.is(warnings[0].severity, 'warning');
  t.is(warnings[0].code, 'E_UNSUPPORTED_SEMANTIC');
  t.regex(warnings[0].message, /cookie/);
  t.regex(warnings[0].message, /sessionId/);
});

test('GenerateError.isGenerateError detects upgraded errors via the cross-realm marker', async t => {
  const error = await t.throwsAsync(async () => {
    await generate({
      inputPath: fixture('petstore-minimal.openapi.yaml'),
      emit: [],
    });
  });
  t.true(GenerateError.isGenerateError(error));
  t.false(GenerateError.isGenerateError(new Error('plain')));
  t.false(GenerateError.isGenerateError(null));
  t.false(GenerateError.isGenerateError(undefined));
  t.false(GenerateError.isGenerateError({ code: 'E_INVALID_OPTION' }));
});

test('GenerateError marker constant is stamped by the constructor alone', async t => {
  // `lib/error-marker.json` is the only source of the marker; the Rust side
  // neither embeds nor reads it, `GenerateError`'s constructor stamps it.
  // The constant must stay a non-empty string so the cross-realm marker
  // survives the boundary.
  const marker = JSON.parse(
    fs.readFileSync(path.join(__dirname, '..', 'lib', 'error-marker.json'), 'utf8'),
  );
  t.is(typeof marker.marker, 'string');
  t.true(marker.marker.length > 0);

  // The marker property is non-enumerable on a GenerateError instance —
  // expose it only via OwnPropertyDescriptors so that JSON.stringify(err)
  // doesn't leak the sentinel into application output.
  const error = (await t.throwsAsync(async () => {
    await generate({ inputPath: fixture('petstore-minimal.openapi.yaml'), emit: [] });
  }))!;
  const descriptor = Object.getOwnPropertyDescriptor(error, marker.marker);
  t.truthy(descriptor, 'marker property must be present on the GenerateError instance');
  t.is(descriptor?.enumerable, false);
  t.is(descriptor?.value, true);
});

test('generate is the public API name (replaces generateNative)', t => {
  const mod = createRequire(import.meta.url)('../lib/index.js');
  t.is(typeof mod.generate, 'function');
  t.is(mod.generateNative, undefined);
});

test('index.d.ts exposes the generate contract (emit array, contents-only artifacts, GenerateError class)', t => {
  const contract = fs.readFileSync(path.join(__dirname, '..', 'index.d.ts'), 'utf8');

  t.true(
    contract.includes(
      'export declare function generate(options: GenerateOptions): Promise<GenerateResult>',
    ),
  );
  t.true(contract.includes('export interface GenerateOptions {'));
  t.true(contract.includes('inputPath?: string'));
  t.true(contract.includes('inputContents?: string'));
  t.true(contract.includes('displayPath?: string'));
  t.true(contract.includes('inputFormat?: InputFormat'));
  t.true(contract.includes('outputPath?: string'));
  t.true(contract.includes('emit?: Array<EmitTarget>'));
  t.true(contract.includes('mappedTypes?: Array<MappedType>'));
  t.true(contract.includes('export interface GenerateResult {'));
  t.true(contract.includes('summary: GenerateSummary'));
  t.true(contract.includes('diagnostics: Array<GeneratorDiagnostic>'));
  t.true(contract.includes('artifacts: Array<GeneratedArtifact>'));
  t.true(contract.includes('export interface GeneratedArtifact {'));
  t.true(contract.includes('normalizedSourcePath: string'));
  t.true(contract.includes('export declare class GenerateError extends Error {'));
  t.true(contract.includes('export interface MappedType {'));
  t.true(contract.includes('  schema: string'));
  t.true(contract.includes('  import: string'));
  t.true(contract.includes('  type: string'));
  t.true(contract.includes('  alias?: string'));
});

test('naming.methodName strips verb prefix end-to-end (posts_listAll → listAll)', async t => {
  const result = await generate({
    inputPath: fixture('verb-prefix.openapi.yaml'),
    emit: ['models', 'angular'],
    naming: {
      methodName: {
        from: '{operationId}',
        parse: /^[^_]+_(?<rest>.+)$/,
        format: '{capture.rest}',
        case: 'camel',
      },
    },
  });
  const service = result.artifacts.find(
    (a: { path: string }) => a.path === 'rest/post.rest.ts',
  );
  t.assert(service, 'expected post service artifact');
  t.regex(service!.contents, /\blistAll\b/);
  t.regex(service!.contents, /\bcreate\b/);
  t.notRegex(service!.contents, /\bposts_listAll\b/);
  t.notRegex(service!.contents, /\bposts_create\b/);
});

test.serial('generate fetches an https URL and uses it as displayPath', async t => {
  const yaml = 'openapi: 3.0.3\ninfo: { title: Fetched, version: 1.0.0 }\npaths: {}\n';
  __setFetchImplForTest(
    async () => new Response(yaml, { headers: { 'content-type': 'application/yaml' } }),
  );
  try {
    const result = await generate({
      inputPath: 'https://example.com/spec.yaml',
      emit: ['models'],
    });
    t.is(result.summary.title, 'Fetched');
    t.is(result.summary.normalizedSourcePath, 'https://example.com/spec.yaml');
  } finally {
    __setFetchImplForTest(null);
  }
});

test.serial('generate rejects http URLs with E_INPUT_INVALID', async t => {
  __setFetchImplForTest(async () => new Response('{}'));
  try {
    const err = await t.throwsAsync(async () => {
      await generate({
        inputPath: 'http://example.com/spec.json',
        emit: ['models'],
      });
    });
    t.is((err as any).code, 'E_INPUT_INVALID');
    t.true((err as any).message.includes('https://'));
  } finally {
    __setFetchImplForTest(null);
  }
});

test.serial(
  'generate rejects both inputContents and a URL inputPath without fetching',
  async t => {
    let fetched = false;
    __setFetchImplForTest(async () => {
      fetched = true;
      return new Response('openapi: 3.0.3\n', {
        headers: { 'content-type': 'application/yaml' },
      });
    });
    try {
      const err = await t.throwsAsync(async () => {
        await generate({
          inputPath: 'https://example.com/spec.yaml',
          inputContents: 'openapi: 3.0.3\n',
          displayPath: 'inline',
          emit: ['models'],
        } as any);
      });
      t.is((err as any).code, 'E_INVALID_OPTION');
      t.is((err as any).subcode, 'shape');
      t.false(
        fetched,
        'fetchInput must not be called when validation would reject the call anyway',
      );
    } finally {
      __setFetchImplForTest(null);
    }
  },
);

// Three concurrent calls against distinct temp dirs and one on-disk
// spec: catches shared mutable state in `prepareOptions` or below it.
test('generate is safe to run concurrently across distinct outputs', async t => {
  const baseOptions = {
    inputPath: fixture('petstore-minimal.openapi.yaml'),
    emit: [...DEFAULT_EMIT] as ('models' | 'angular')[],
    naming: { methodName: '{operationId}' },
  };

  await withTempDir(async dirA => {
    await withTempDir(async dirB => {
      await withTempDir(async dirC => {
        const sharedNaming = baseOptions.naming;
        const [a, b, c] = await Promise.all([
          generate({ ...baseOptions, outputPath: dirA }),
          generate({ ...baseOptions, outputPath: dirB }),
          generate({ ...baseOptions, outputPath: dirC }),
        ]);

        // `prepareOptions` spreads rather than writing back.
        t.is(baseOptions.naming, sharedNaming);
        t.deepEqual(baseOptions.naming, { methodName: '{operationId}' });

        const namesA = a.artifacts.map(art => art.path).sort();
        const namesB = b.artifacts.map(art => art.path).sort();
        const namesC = c.artifacts.map(art => art.path).sort();
        t.deepEqual(namesA, namesB);
        t.deepEqual(namesA, namesC);
        t.true(namesA.includes('model.ts'));

        for (const dir of [dirA, dirB, dirC]) {
          t.true(
            fs.existsSync(path.join(dir, 'model.ts')),
            `model.ts must exist in ${dir}`,
          );
        }

        // Contents are byte-identical across all three calls.
        const aByPath = new Map(a.artifacts.map(art => [art.path, art.contents]));
        for (const art of b.artifacts) {
          t.is(aByPath.get(art.path), art.contents, `mismatch at ${art.path}`);
        }
      });
    });
  });
});

// ── layout ──────────────────────────────────────────────────────────────────

test('generate layout operations emits one file per operation plus a barrel and no class', async t => {
  const result = await generate({
    inputPath: fixture('petstore-minimal.openapi.yaml'),
    emit: [...DEFAULT_EMIT],
    layout: ['operations'],
  });
  t.deepEqual(
    result.artifacts.map(a => a.path),
    [
      'model.ts',
      'rest.model.ts',
      'rest.util.ts',
      'rest.validate.ts',
      'rest/pet/list-pets.ts',
      'rest/pet/index.ts',
    ],
  );
  const operation = result.artifacts.find(a => a.path === 'rest/pet/list-pets.ts')!;
  t.true(
    operation.contents.includes(
      'export const listPets = /* @__PURE__ */ defineOperation.zeroArg<void>(',
    ),
  );
  t.true(
    operation.contents.includes("import { defineOperation } from '../../rest.util';"),
  );
  const barrel = result.artifacts.find(a => a.path === 'rest/pet/index.ts')!;
  t.true(barrel.contents.endsWith("export * from './list-pets';\n"));
});

test('generate layout services,operations adds the class built from the barrel', async t => {
  const result = await generate({
    inputPath: fixture('petstore-minimal.openapi.yaml'),
    emit: [...DEFAULT_EMIT],
    layout: ['services', 'operations'],
  });
  const paths = result.artifacts.map(a => a.path);
  t.true(paths.includes('rest/pet/list-pets.ts'));
  t.true(paths.includes('rest/pet/index.ts'));
  const service = result.artifacts.find(a => a.path === 'rest/pet.rest.ts')!;
  t.true(service.contents.includes("import * as ops from './pet';"));
  t.true(service.contents.includes('readonly listPets = ops.listPets.withInjector();'));
  t.false(service.contents.includes('requestFactory'));
});

test('generate layout services is the default and matches an explicit services layout', async t => {
  const implicit = await generate({
    inputPath: fixture('petstore-minimal.openapi.yaml'),
    emit: [...DEFAULT_EMIT],
  });
  const explicit = await generate({
    inputPath: fixture('petstore-minimal.openapi.yaml'),
    emit: [...DEFAULT_EMIT],
    layout: ['services'],
  });
  t.deepEqual(explicit.artifacts, implicit.artifacts);
  t.deepEqual(
    implicit.artifacts.map(a => a.path),
    ['model.ts', 'rest.model.ts', 'rest.util.ts', 'rest.validate.ts', 'rest/pet.rest.ts'],
  );
});

test('generate rejects the operations layout without the angular emit target', async t => {
  const err = await t.throwsAsync(() =>
    generate({
      inputPath: fixture('petstore-minimal.openapi.yaml'),
      emit: ['models'],
      layout: ['services', 'operations'],
    }),
  );
  t.is((err as any).code, 'E_INVALID_OPTION');
  t.true(err!.message.includes("layout 'operations' requires the 'angular' emit target"));
});

test('generate rejects an unknown layout value at the wrapper boundary', async t => {
  const err = await t.throwsAsync(() =>
    generate({
      inputPath: fixture('petstore-minimal.openapi.yaml'),
      emit: [...DEFAULT_EMIT],
      layout: ['flat'] as any,
    }),
  );
  t.is((err as any).code, 'E_INVALID_OPTION');
  t.is((err as any).subcode, 'shape');
  t.true(err!.message.includes("invalid entry 'flat'"));
});

test('generate rejects a non-array layout at the wrapper boundary', async t => {
  const err = await t.throwsAsync(() =>
    generate({
      inputPath: fixture('petstore-minimal.openapi.yaml'),
      emit: [...DEFAULT_EMIT],
      layout: 'operations' as any,
    }),
  );
  t.is((err as any).code, 'E_INVALID_OPTION');
  t.is((err as any).subcode, 'shape');
  t.true(err!.message.includes('layout must be an array'));
});

test('generate rejects an empty layout list', async t => {
  const err = await t.throwsAsync(() =>
    generate({
      inputPath: fixture('petstore-minimal.openapi.yaml'),
      emit: [...DEFAULT_EMIT],
      layout: [],
    }),
  );
  t.is((err as any).code, 'E_INVALID_OPTION');
  t.true(err!.message.includes('layout must include at least one entry'));
});

test('generate rejects an operation named default under layout operations', async t => {
  const err = await t.throwsAsync(() =>
    generate({
      inputPath: fixture('default-method-name.openapi.yaml'),
      emit: [...DEFAULT_EMIT],
      layout: ['operations'],
    }),
  );
  t.is((err as any).code, 'E_POLICY_VIOLATION');
  t.is((err as any).subcode, 'reserved-identifier');
  t.true(err!.message.includes('naming.methodName'));
});

test('generate rejects two operations resolving to one method name in a group', async t => {
  const err = await t.throwsAsync(() =>
    generate({
      inputPath: fixture('petstore-rich.openapi.yaml'),
      emit: [...DEFAULT_EMIT],
      naming: { methodName: 'same' },
    }),
  );
  t.is((err as any).code, 'E_POLICY_VIOLATION');
  t.is((err as any).subcode, 'naming-resolution');
  t.true(err!.message.includes("methodName 'same' resolves for both"));
});

test.serial(
  'generate layout services,operations emits standalone operations that type-check in a consumer project',
  async t => {
    resetAngularConsumerGeneratedDir();

    await generate({
      inputPath: fixture('reserved-method-name.openapi.yaml'),
      outputPath: angularConsumerGeneratedDir,
      emit: [...DEFAULT_EMIT],
      layout: ['services', 'operations'],
    });

    execFileSync(
      process.execPath,
      [
        path.join(__dirname, '..', 'node_modules', 'typescript', 'bin', 'tsc'),
        '-p',
        path.join(__dirname, 'angular-consumer', 'tsconfig.standalone.json'),
      ],
      {
        cwd: path.join(__dirname, 'angular-consumer'),
        stdio: 'pipe',
      },
    );
    t.pass('tsc type-checked the standalone-operation proof successfully');
  },
);
